rgbd_gaze_calibration:
  ros__parameters:
    eyeball_radius:
      min: 0.012
      max: 0.014
    sample_consensus:
      distance_threshold: 0.004
      probability: 0.99999
      max_iterations: 100000

    publish_eyelid_pc: true
    publish_markers: true
    use_sim_time: false
