rgbd_gaze:
  ros__parameters:
    user:
      id: user0

      eyes:
        left:
          eyeball_centre:
            x: -0.033307
            y: -0.001995
            z: -0.006030
          eyeball_radius: 0.013438

          kappa:
            alpha: 0.0
            beta: 0.0
          distance_eyeball_cornea: 0.0

        right:
          eyeball_centre:
            x: 0.033608
            y: -0.002530
            z: -0.003689
          eyeball_radius: 0.013359

          kappa:
            alpha: 0.0
            beta: 0.0
          distance_eyeball_cornea: 0.0

    broadcast_tf: false
    publish_markers: true
    use_sim_time: false
